version: 2.0

jobs:
    build:
        docker:
            - image: circleci/node:6.10
        steps:
            - checkout
            - restore_cache:
                key: node-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                key: node-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Run Tests
                command: npm test
